In [12]:
#AI-TECHGYM-1-15-A-2
#自然言語処理

#インポート
from gensim.models import KeyedVectors

# ダウンロード先のパスを指定
MODEL_FILENAME = "./stanby-jobs-200d-word2vector.bin"
w2v = KeyedVectors.load_word2vec_format(MODEL_FILENAME, binary=True)

print("連想ゲームのはじめの単語を入力してください(終了:Q)")

while True:
    #インプット
    word = input()
    if word == 'Q':
        break

    try:
        job = w2v.most_similar(word,topn=1)
    except :
        print("モデルにない単語なのでもう一度入力してください。\n")
        continue

    #連想した単語
    word_sim = job[0][0]

    #マジカルバナナ
    print("'" + word + "'と言ったら'" + word_sim + "'です。\n")
    print("'" + word_sim + "'と言ったら？'\n")


連想ゲームのはじめの単語を入力してください(終了:Q)


 単語


'単語'と言ったら'文章'です。

'文章'と言ったら？'



 文学


'文学'と言ったら'史学'です。

'史学'と言ったら？'



 織田信長


モデルにない単語なのでもう一度入力してください。



 信長


'信長'と言ったら'観音新'です。

'観音新'と言ったら？'



 仏教


'仏教'と言ったら'キリスト教'です。

'キリスト教'と言ったら？'



 天使


'天使'と言ったら'ちぐさ'です。

'ちぐさ'と言ったら？'



 植物


'植物'と言ったら'草花'です。

'草花'と言ったら？'



 団子


'団子'と言ったら'わらび餅'です。

'わらび餅'と言ったら？'



 ワラビー


モデルにない単語なのでもう一度入力してください。



 q


'q'と言ったら'd0'です。

'd0'と言ったら？'



 Q


array([ 0.32957697,  0.2754701 , -0.6299979 , -0.11524674,  0.00619126,
       -0.62674457,  0.57847244, -0.15302496, -0.5174251 ,  0.18322502,
        0.08868922, -0.5265856 ,  0.11648794,  0.2975874 , -0.03275626,
        0.33755222, -0.5483359 , -0.435173  , -0.00661894,  0.0720847 ,
        0.09870452,  0.13164671, -0.3955186 ,  0.29221842,  0.0708501 ,
       -0.20181936, -0.5183477 ,  0.58808976, -0.40646732,  0.5056305 ,
       -0.2916558 , -0.38934985, -0.0780085 , -0.22913045, -0.26756656,
       -0.10340966, -0.2509233 ,  0.41328976, -0.3469264 ,  0.30026188,
        0.6191483 ,  0.05545525,  0.02608356, -0.3332693 , -0.51168776,
        0.30928332, -0.57611364,  0.27011678, -0.5463228 , -0.06749955,
       -0.065115  , -0.03566641, -0.50520825, -0.44641566,  0.21783476,
        0.44777417,  0.17348449, -0.8166766 , -0.46550477, -0.49684247,
       -0.09062086, -0.16974933,  0.78963244,  0.07520461, -0.07232548,
        0.2008646 ,  0.09928322,  0.13634354,  0.9635173 , -0.06

In [39]:
model.wv.n_similarity('老人', '海')

KeyError: "Key '老' not present"

In [34]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [89]:
sc = StandardScaler()
X_std = sc.fit_transform(cancer.data[:,0].reshape(-1,1))
print(X_std[:5])

[[ 1.09706398]
 [ 1.82982061]
 [ 1.57988811]
 [-0.76890929]
 [ 1.75029663]]


In [90]:
sc = StandardScaler()
X_std = sc.fit_transform(cancer.data)
print(X_std[:5])

[[ 1.09706398e+00 -2.07333501e+00  1.26993369e+00  9.84374905e-01
   1.56846633e+00  3.28351467e+00  2.65287398e+00  2.53247522e+00
   2.21751501e+00  2.25574689e+00  2.48973393e+00 -5.65265059e-01
   2.83303087e+00  2.48757756e+00 -2.14001647e-01  1.31686157e+00
   7.24026158e-01  6.60819941e-01  1.14875667e+00  9.07083081e-01
   1.88668963e+00 -1.35929347e+00  2.30360062e+00  2.00123749e+00
   1.30768627e+00  2.61666502e+00  2.10952635e+00  2.29607613e+00
   2.75062224e+00  1.93701461e+00]
 [ 1.82982061e+00 -3.53632408e-01  1.68595471e+00  1.90870825e+00
  -8.26962447e-01 -4.87071673e-01 -2.38458552e-02  5.48144156e-01
   1.39236330e-03 -8.68652457e-01  4.99254601e-01 -8.76243603e-01
   2.63326966e-01  7.42401948e-01 -6.05350847e-01 -6.92926270e-01
  -4.40780058e-01  2.60162067e-01 -8.05450380e-01 -9.94437403e-02
   1.80592744e+00 -3.69203222e-01  1.53512599e+00  1.89048899e+00
  -3.75611957e-01 -4.30444219e-01 -1.46748968e-01  1.08708430e+00
  -2.43889668e-01  2.81189987e-01]
 [ 1.5

In [49]:
#AI-TECHGYM-1-4-A-3
#教師なし学習 k-mean法

# データ加工・処理・分析ライブラリ
import pandas as pd
from pandas import Series, DataFrame

# 可視化ライブラリ
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# k-means法を使うためのインポート
from sklearn.cluster import KMeans

# データがあるurl の指定
file_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00468/online_shoppers_intention.csv'

# データを取得して展開する
#対象データを読み込み
shoppers= pd.read_csv(file_url)

# データの列の絞り込み
shoppers_sub = shoppers[['Administrative_Duration','Informational_Duration','ProductRelated_Duration','Region','SpecialDay']]

# KMeansクラスの初期化
kmeans = KMeans(init='random', n_clusters=6, random_state=0)

# クラスターの重心を計算
kmeans.fit(shoppers_sub)

# クラスター番号をpandasのSeriesオブジェクトに変換
labels = pd.Series(kmeans.labels_, name='cluster_number')

# 金融機関のデータにクラスター番号のデータを結合
shoppers_with_cluster = pd.concat([shoppers, labels], axis=1)

# 分割のための区切りを設定
bins = [0,0.2,0.4,0.6,0.8,1]

# 上の区切りをもとに金融機関のデータを分割し、qcut_age変数に各データの年齢層を設定
qcut_sp = pd.cut(shoppers_with_cluster.SpecialDay, bins, right=False)

# クラスタ番号と年齢層を結合
df = pd.concat([shoppers_with_cluster.cluster_number, qcut_sp], axis=1)

# クラスタ番号と年齢層を軸に集計し、年齢層を列に設定
cross_cluster_sp = df.groupby(['cluster_number', 'SpecialDay']).size().unstack().fillna(0)
display(cross_cluster_sp)

# 分割のための区切りを設定
bins_2 = [1,2,3,4,5,6,7,8,9]

# 上の区切りをもとに金融機関のデータを分割し、qcut_age変数に各データの年齢層を設定
qcut_r = pd.cut(shoppers_with_cluster.Region, bins_2, right=False, labels=[1,2,3,4,5,6,7,8])

# クラスタ番号と年齢層を結合
df = pd.concat([shoppers_with_cluster.cluster_number, qcut_r], axis=1)

# クラスタ番号と年齢層を軸に集計し、年齢層を列に設定
cross_cluster_r = df.groupby(['cluster_number', 'Region']).size().unstack().fillna(0)
display(cross_cluster_r)


SpecialDay      [0.0, 0.2)  [0.2, 0.4)  [0.4, 0.6)  [0.6, 0.8)  [0.8, 1.0)
cluster_number                                                            
0                      386           6           7           2          15
1                       10           0           0           0           0
2                     1096           9          28          26          20
3                     2807          49          48          83          71
4                     6657         114         159         240         218
5                      123           0           1           0           1

Region             1    2     3    4    5    6    7    8
cluster_number                                          
0                181   39    83   35   12   25   17   15
1                  8    0     1    1    0    0    0    0
2                464  119   239  110   27   64   78   39
3               1145  302   616  302   79  212  207  120
4               2912  667  1444  727  196  500  453  260
5                 70    9    20    7    4    4    6    0